# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Minecraft
minecraft_version=26.2

# Project
mod_version=0.9.7+26.2-fabric
maven_group=net.hallowed
archives_base_name=neatly-better

# Fabric
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.152.1+26.2

# Integrations
forgeconfigapiport_version=rSd3GiG8
modmenu_version=njXb639R
elytratrims_version=X4BX7O9a