# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Minecraft
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1


# Project
mod_version=0.8.5
maven_group=net.hallowed
archives_base_name=old-ways

# Fabric
fabric_version=0.133.4+1.21.8
loader_version=0.17.2
loom_version=1.11-SNAPSHOT
fabric_api_version=0.133.1+1.21.8

# Mod Implementation
betterf3_version=15.0.0