# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Minecraft
minecraft_version=26.1.1

# Project
mod_version=0.9.4+26.1.x-fabric
maven_group=net.hallowed
archives_base_name=neatly-better

# Fabric
loader_version=0.18.6
loom_version=1.15-SNAPSHOT
fabric_api_version=0.145.4+26.1.1

# Integrations
forgeconfigapiport_version=RXbL43Lt
modmenu_version=18.0.0-alpha.8
framework_version=7866653
backpacked_version=7866692
elytratrims_version=q7SmWLkn
bbe_version=lex0PhIz